//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VetenarienLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class consultation
    {
        public consultation()
        {
            this.jobs = new HashSet<job>();
        }
    
        public int consultation_ID { get; set; }
        public System.DateTime startDate { get; set; }
        public System.DateTime endDate { get; set; }
        public string descriptions { get; set; }
        public string vetDescriptions { get; set; }
        public Nullable<int> pet_ID { get; set; }
    
        public virtual pet pet { get; set; }
        public virtual ICollection<job> jobs { get; set; }
    }
}
