//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VetenarienLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class job
    {
        public job()
        {
            this.consultations = new HashSet<consultation>();
        }
    
        public int job_ID { get; set; }
        public string name { get; set; }
        public decimal price { get; set; }
    
        public virtual ICollection<consultation> consultations { get; set; }
    }
}
