//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VetenarienLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class pet
    {
        public pet()
        {
            this.consultations = new HashSet<consultation>();
        }
    
        public int pet_ID { get; set; }
        public string name { get; set; }
        public Nullable<System.DateTime> birthday { get; set; }
        public Nullable<bool> sex { get; set; }
        public Nullable<int> petOwner { get; set; }
        public Nullable<int> petSpecies { get; set; }
    
        public virtual ICollection<consultation> consultations { get; set; }
        public virtual petOwner petOwner1 { get; set; }
        public virtual petSpecy petSpecy { get; set; }
    }
}
